[package]
name = "bitors"
version = "2.0.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
description = "A crate for parsing and creating BitTorrent metainfo files (`.torrent`)"
repository = "https://github.com/zradj/bitors"
categories = ["encoding", "parser-implementations", "filesystem"]
keywords = ["bittorrent", "torrent", "bencode", "metainfo", "p2p"]

[dependencies]
data-encoding = "2.11.0"
digest-io = "0.1.0"
percent-encoding = "2.3.2"
sha1 = "0.11.0"
thiserror = "2.0.18"
url = "2.5.8"
walkdir = "2.5.0"
