//! Top-level error type for the `bitors` crate.
//!
//! [`Error`] aggregates the two sub-module error types so that code which calls
//! both the [`bencode`](crate::bencode) parser and the [`torrent`](crate::torrent)
//! layer can use a single `?` operator and a single error type in its return
//! signature.
//!
//! If you only use one layer (e.g. the Bencode parser in isolation) you can
//! return [`bencode::Error`](crate::bencode::Error) or
//! [`torrent::Error`](crate::torrent::Error) directly to keep error handling
//! more precise.

use std::io;

use thiserror::Error;

/// The top-level error enum, aggregating all sub-module errors.
///
/// Both variants are constructed automatically via `From` implementations
/// generated by [`thiserror`], so the `?` operator will convert a
/// [`bencode::Error`](crate::bencode::Error) or a
/// [`torrent::Error`](crate::torrent::Error) into this type without any manual
/// mapping.
#[derive(Debug, Error)]
pub enum Error {
    /// An error that originated in the [`bencode`](crate::bencode) parsing layer.
    #[error("Bencode parsing error: {0}")]
    Bencode(#[from] crate::bencode::Error),
    /// An error that originated in the [`torrent`](crate::torrent) parsing or
    /// construction layer.
    #[error("Torrent error: {0}")]
    Torrent(#[from] crate::torrent::Error),
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),
}
